### ISSUE TITLE
Flare v2.0.0 Roadmap

### ISSUE THREAD

**Issue by velocity23** [va-net/flare#312]
# Summary

Flare 2 is all about improving the design and customisability of Flare. By reworking significant amounts of Flare's backend, we will be introducing theming and a variety of themes to make Flare look amazing. Furthermore, we'll be adding some community-requested features such as Pilot and PIREP Deletion, PIREP Comments, and a way to confirm the information provided by ACARS.

# Feature List

> 📄 In Planning
> 👨‍💻 In Progress
> ✅ Complete

| Status | Feature            | Type          | Issue | Assignee    |
| ------ | ------------------ | ------------- | ----- | ----------- |
| ✅     | Theming            | Epic          | #317  | @velocity23 |
| ✅     | Pilot Awards       | Feature       | #318  | @velocity23         |
| ✅     | Pilot Deletion     | Update        | #269  | @velocity23         |
| ✅     | PIREP Deletion     | Update        | #291  | @velocity23         |
| ✅     | PIREP Comments     | Feature       | #310  | @velocity23 |
| ✅     | ACARS Confirmation | Default Theme | #307  | @velocity23          |

# Pre-Release Checklist

-   [x] Push v1.2 patch update to restructure updater to make life easier and that uses legacy plugins branch
-   [x] Update updates file to account for the updater restructure
-   [x] #354
-   [x] #355

# Things to Test (so far)

Everything, but in particular:

-   No broken links
-   All forms work when submitted
-   All pages appear as expected
-   ACARS
-   Codeshares
-   Events Admin

# Timeline

~~Due to the fact we are reworking much of Flare and creating multiple themes for this release, we estimate (but cannot guarantee) that Flare v1.3 will take approximately 4-5 months.~~

**Update 30MAY21:** We are just beginning to shift our focus back to Flare after completing VANet v2. Please stand by as we work to make this release incredible. We estimate it will be ready by the end of July, and in testing no later than half way through June.

**Comment by samdog2727** [comment]
@velocity23 , I was wondering if there was any chance for a "Remember Me" feature so you don't have to put in your username and password every time you get logged out.

**Comment by velocity23** [comment]
Not in this update, we've already got enough going on

**Comment by Raveesh1505** [comment]
Can the pilot leaderboard be visible to all the pilots? If not in this update, may be next can feature it.

**Comment by velocity23** [comment]
Maybe as a plugin, not all VAs want to encourage competition.

**Comment by Raveesh1505** [comment]
> Maybe as a plugin, not all VAs want to encourage competition.

Yeah sure, that would be awesome!

**Comment by BaptisteDesmet** [comment]
Have you thinking to add a thing like an `pilot leaderboard` ?

**Comment by velocity23** [comment]
### Pre-Release Checklist

- [ ] Push v1.2 patch update to restructure updater to make life easier and that uses legacy plugins branch
- [ ] Update updates file to account for the updater restructure
- [ ] Make plugins work (new system using VANet Flare API?)
- [ ] Make at least 1 new theme

(No we're not close to release, I'm just starting a checklist so I don't forget anything)
